# Generated by Django 5.2.5 on 2025-08-07 10:57

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_generated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ImageSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('original_markdown', models.TextField()),
                ('easy_read_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('original_path', models.CharField(max_length=500)),
                ('processed_path', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('file_format', models.CharField(choices=[('PNG', 'PNG'), ('SVG', 'SVG')], max_length=10)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.imageset')),
            ],
            options={
                'ordering': ['set__name', 'filename'],
                'unique_together': {('set', 'filename')},
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('pdf_uploaded', models.BooleanField(default=False)),
                ('pdf_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('input_content_size', models.IntegerField(blank=True, null=True)),
                ('sentences_generated', models.IntegerField(default=0)),
                ('exported_result', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['ip_address', 'started_at'], name='api_userses_ip_addr_ba7a53_idx'), models.Index(fields=['started_at'], name='api_userses_started_b5c8af_idx')],
            },
        ),
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_type', models.CharField(choices=[('image', 'Image Embedding'), ('text', 'Text Embedding')], max_length=10)),
                ('vector', pgvector.django.vector.VectorField(dimensions=2000)),
                ('provider_name', models.CharField(default='cohere_bedrock', max_length=100)),
                ('model_name', models.CharField(default='cohere.embed-multilingual-v3', max_length=100)),
                ('embedding_dimension', models.IntegerField(default=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='api.image')),
            ],
            options={
                'ordering': ['image', 'embedding_type', 'provider_name', 'model_name'],
                'indexes': [models.Index(fields=['provider_name', 'model_name', 'embedding_type'], name='api_embeddi_provide_02502d_idx'), models.Index(fields=['image', 'embedding_type', 'provider_name'], name='api_embeddi_image_i_c25746_idx'), models.Index(fields=['embedding_dimension'], name='api_embeddi_embeddi_926c95_idx')],
                'unique_together': {('image', 'embedding_type', 'provider_name', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='SessionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('pdf_upload', 'PDF Upload'), ('content_input', 'Content Input'), ('page_process', 'Page Processing'), ('content_validate', 'Content Validation'), ('sentence_revise', 'Sentence Revision'), ('image_search', 'Image Search'), ('image_select', 'Image Selection'), ('image_change', 'Image Change'), ('content_save', 'Content Save'), ('content_export', 'Content Export'), ('image_upload', 'Image Upload'), ('image_generate', 'Image Generation')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.usersession')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['session', 'event_type'], name='api_session_session_878824_idx'), models.Index(fields=['timestamp'], name='api_session_timesta_66260f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImageSetSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('image_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.imageset')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_set_selections', to='api.usersession')),
            ],
            options={
                'ordering': ['selected_at'],
                'unique_together': {('session', 'image_set')},
            },
        ),
        migrations.CreateModel(
            name='ImageSelectionChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_index', models.IntegerField()),
                ('old_ranking', models.IntegerField(blank=True, null=True)),
                ('new_ranking', models.IntegerField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('new_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_selections', to='api.image')),
                ('old_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_selections', to='api.image')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_changes', to='api.usersession')),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['session', 'sentence_index'], name='api_imagese_session_46c1cc_idx'), models.Index(fields=['changed_at'], name='api_imagese_changed_0587c4_idx')],
            },
        ),
    ]
