# Generated by Django 5.2 on 2025-08-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_processedcontent_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file_format',
            field=models.CharField(choices=[('PNG', 'PNG'), ('SVG', 'SVG'), ('JPG', 'JPEG'), ('GIF', 'GIF'), ('WEBP', 'WebP')], max_length=10),
        ),
    ]
