# Generated by Django 5.2 on 2025-05-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_processedcontent_delete_easyreadresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="processedcontent",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
