# Generated by Django 5.2.7 on 2025-10-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_image_file_format'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageMetadata',
        ),
        migrations.AlterField(
            model_name='sessionevent',
            name='event_type',
            field=models.CharField(choices=[('pdf_upload', 'PDF Upload'), ('content_input', 'Content Input'), ('page_process', 'Page Processing'), ('content_validate', 'Content Validation'), ('sentence_revise', 'Sentence Revision'), ('image_search', 'Image Search'), ('image_search_batch', 'Batch Image Search'), ('image_select', 'Image Selection'), ('image_change', 'Image Change'), ('image_allocation_applied', 'Image Allocation Applied'), ('content_save', 'Content Save'), ('content_export', 'Content Export'), ('image_upload', 'Image Upload'), ('image_generate', 'Image Generation')], max_length=50),
        ),
    ]
