# Generated by Django 5.2 on 2025-05-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_imagemetadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagemetadata",
            name="is_generated",
            field=models.BooleanField(default=False),
        ),
    ]
