# Generated by Django 5.2.5 on 2025-11-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_imagemetadata_alter_sessionevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageset',
            name='no_of_images',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
