# Generated by Django 5.2.9 on 2026-01-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_imagemetadata_alter_sessionevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitelistedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, help_text='Optional name for reference', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive emails cannot request OTP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Whitelisted Email',
                'verbose_name_plural': 'Whitelisted Emails',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='OTPToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('token', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'token', 'used'], name='api_otptoke_email_407306_idx'), models.Index(fields=['expires_at'], name='api_otptoke_expires_b3f6d3_idx')],
            },
        ),
    ]
