# Generated by Django 6.0.1 on 2026-02-09 17:26

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_whitelistedemail_otptoken'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='embedding',
            index=pgvector.django.indexes.HnswIndex(fields=['vector'], name='idx_embedding_vector_cosine', opclasses=['vector_cosine_ops']),
        ),
    ]
