# Generated by Django 5.2 on 2025-07-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_pgvector_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='embedding',
            options={'ordering': ['image', 'embedding_type', 'provider_name', 'model_name']},
        ),
        migrations.AlterUniqueTogether(
            name='embedding',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='embedding',
            name='embedding_dimension',
            field=models.IntegerField(default=1280),
        ),
        migrations.AddField(
            model_name='embedding',
            name='provider_name',
            field=models.CharField(default='openclip', max_length=100),
        ),
        migrations.AlterField(
            model_name='embedding',
            name='model_name',
            field=models.CharField(default='openclip-vit-b-32', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='embedding',
            unique_together={('image', 'embedding_type', 'provider_name', 'model_name')},
        ),
        migrations.AddIndex(
            model_name='embedding',
            index=models.Index(fields=['provider_name', 'model_name', 'embedding_type'], name='api_embeddi_provide_02502d_idx'),
        ),
        migrations.AddIndex(
            model_name='embedding',
            index=models.Index(fields=['image', 'embedding_type', 'provider_name'], name='api_embeddi_image_i_c25746_idx'),
        ),
        migrations.AddIndex(
            model_name='embedding',
            index=models.Index(fields=['embedding_dimension'], name='api_embeddi_embeddi_926c95_idx'),
        ),
    ]
