# Generated by Django 4.2.7 on 2025-07-17 22:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_backfill_embedding_dimensions"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("pdf_uploaded", models.BooleanField(default=False)),
                ("pdf_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("input_content_size", models.IntegerField(blank=True, null=True)),
                ("sentences_generated", models.IntegerField(default=0)),
                ("exported_result", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["ip_address", "started_at"],
                        name="api_userses_ip_addr_ba7a53_idx",
                    ),
                    models.Index(
                        fields=["started_at"], name="api_userses_started_b5c8af_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SessionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("pdf_upload", "PDF Upload"),
                            ("content_input", "Content Input"),
                            ("page_process", "Page Processing"),
                            ("content_validate", "Content Validation"),
                            ("sentence_revise", "Sentence Revision"),
                            ("image_search", "Image Search"),
                            ("image_select", "Image Selection"),
                            ("image_change", "Image Change"),
                            ("content_save", "Content Save"),
                            ("content_export", "Content Export"),
                            ("image_upload", "Image Upload"),
                            ("image_generate", "Image Generation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("event_data", models.JSONField(blank=True, default=dict)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="api.usersession",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["session", "event_type"],
                        name="api_session_session_878824_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="api_session_timesta_66260f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ImageSetSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.imageset"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_set_selections",
                        to="api.usersession",
                    ),
                ),
            ],
            options={
                "ordering": ["selected_at"],
                "unique_together": {("session", "image_set")},
            },
        ),
        migrations.CreateModel(
            name="ImageSelectionChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentence_index", models.IntegerField()),
                ("old_ranking", models.IntegerField(blank=True, null=True)),
                ("new_ranking", models.IntegerField(blank=True, null=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "new_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="new_selections",
                        to="api.image",
                    ),
                ),
                (
                    "old_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="old_selections",
                        to="api.image",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_changes",
                        to="api.usersession",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "sentence_index"],
                        name="api_imagese_session_46c1cc_idx",
                    ),
                    models.Index(
                        fields=["changed_at"], name="api_imagese_changed_0587c4_idx"
                    ),
                ],
            },
        ),
    ]
