# Generated by Django 4.2.7 on 2025-08-06 10:48

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_migrate_to_pgvector"),
    ]

    operations = [
        # Update vector field to 2000 dimensions for pgvector 0.8.0 compatibility
        migrations.AlterField(
            model_name="embedding",
            name="vector",
            field=pgvector.django.vector.VectorField(dimensions=2000),
        ),
    ]
