# -*- coding: utf-8 -*-
"""
Centralized constants for the EasyRead application.
Loads constants from the shared constants.json file.
"""

import json
import os

def _load_constants():
    """Load constants from the shared JSON file."""
    # In Docker, constants.json is mounted at /app/constants.json
    constants_path = '/app/constants.json'
    try:
        with open(constants_path, 'r', encoding='utf-8') as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError) as e:
        # Fallback constants if JSON file is not found or invalid
        return {
            "disclaimer": {
                "text": "This content was generated by a prototype created at the UNICEF Office of Innovation for evaluation purposes only. The content was generated using Artificial Intelligence and may contain errors, inaccuracies or biases. It is not intended for use in UNICEF programs or by program partners."
            },
            "globalsymbols": {
                "acknowledgement": "Symbols kindly provided by GlobalSymbols - making communication accessible worldwide",
                "url": "https://www.globalsymbols.com"
            }
        }

# Load constants
_CONSTANTS = _load_constants()

# Export individual constants for backward compatibility
DISCLAIMER_TEXT = _CONSTANTS["disclaimer"]["text"]
GLOBALSYMBOLS_ACKNOWLEDGEMENT_TEXT = _CONSTANTS["globalsymbols"]["acknowledgement"]
GLOBALSYMBOLS_URL = _CONSTANTS["globalsymbols"]["url"]