version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: easyread_postgres
    environment:
      POSTGRES_DB: easyread
      POSTGRES_USER: easyread_user
      POSTGRES_PASSWORD: easyread_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    networks:
      - easyread_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U easyread_user -d easyread"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres_data:
    driver: local

networks:
  easyread_network:
    driver: bridge