bind = "0.0.0.0:8000"
workers = 4
pidfile = 'pidfile'
errorlog = 'errorlog'
loglevel = 'info'
accesslog = 'accesslog'
access_log_format = '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'
certfile = '/etc/letsencrypt/live/easyreadadminserver.ooiplayground.com/fullchain.pem'
keyfile = '/etc/letsencrypt/live/easyreadadminserver.ooiplayground.com/privkey.pem'
